/*
【目的】
- 核心理由：GitHub Pages SPA ：狀態分區、Scanner 狀態置於掃描窗下、提案標題選填。
- 權責邊界：[負責]前端 UI/狀態/草稿/日期查詢/提交；[不負責]後端 GAS 修改。
- MWE：不填提案標題也可 submitProposal；歷史查詢送 q='YYYY-MM-DD'。
- 致命錯誤邊界：API timeout、Null DOM、HTML injection、重複送出、相機清理已防護；風險受控。
*/
const CONFIG={API_URL:'https://script.google.com/macros/s/AKfycbxw9Y1y3A7N5CUhgp0ACezB12JXqNPXcssvMTwwWk5C2QeMCvn97UdrueSQ6_Jx0rJG/exec',APP_KEY:'public-mvp-key',CACHE_KEY_VERSION:'proposal_sys_version',CACHE_KEY_DATA:'proposal_sys_master_data',API_TIMEOUT_MS:15000,SCAN_DEBOUNCE_MS:1500};
const S={masterData:{},draftItems:[],scanner:null,lastScanText:'',lastScanAt:0,choices:[],pendingQty:1,submitting:false,syncing:false,historyItems:[],historyLoading:false,detailLoading:false,cameras:[]};
const $=id=>document.getElementById(id),nt=v=>v==null?'':String(v).trim(),pos=(v,f=1)=>{const n=Number(v);return!Number.isFinite(n)||n<=0?f:Math.floor(n)};
function setText(id,t){const e=$(id);if(e)e.textContent=t==null?'':String(t)}
function setStatus(id,m,type){const e=$(id);if(!e)return;e.textContent=m||'';e.className='status';if(type==='error')e.classList.add('error');if(type==='warn')e.classList.add('warn')}
function apiRequest(action,payload={}){const body={action,appKey:CONFIG.APP_KEY,payload},c=new AbortController(),timer=setTimeout(()=>c.abort(),CONFIG.API_TIMEOUT_MS);return fetch(CONFIG.API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body),signal:c.signal}).then(async r=>{const text=await r.text();if(!r.ok)throw new Error(`HTTP ${r.status}: ${text.slice(0,160)}`);try{return JSON.parse(text)}catch(_){throw new Error(`API 回傳不是 JSON：${text.slice(0,160)}`)}}).then(j=>{if(!j||j.success===false)throw new Error(j&&j.message?j.message:'API 失敗');return j.data}).catch(e=>{if(e.name==='AbortError')throw new Error('API 逾時');throw e}).finally(()=>clearTimeout(timer))}
async function syncMasterData(force=false){if(S.syncing)return;S.syncing=true;const b=$('btn-sync');if(b)b.disabled=true;try{setStatus('system-status','同步主檔中...','warn');const rv=await apiRequest('getMasterVersion'),lv=localStorage.getItem(CONFIG.CACHE_KEY_VERSION);if(force||rv!==lv){const arr=await apiRequest('getMasterSnapshot');if(!Array.isArray(arr))throw new Error('主檔快照格式錯誤');const map={};arr.forEach(i=>{const barcode=nt(i.barcode),itemId=nt(i.itemId),name=nt(i.name);if(barcode&&itemId&&name)map[barcode]={barcode,itemId,name}});S.masterData=map;localStorage.setItem(CONFIG.CACHE_KEY_DATA,JSON.stringify(map));localStorage.setItem(CONFIG.CACHE_KEY_VERSION,String(rv||''));setStatus('system-status',`主檔同步完成：${Object.keys(map).length} 筆`,'ok')}else{S.masterData=JSON.parse(localStorage.getItem(CONFIG.CACHE_KEY_DATA)||'{}');setStatus('system-status',`主檔已使用快取：${Object.keys(S.masterData).length} 筆`,'ok')}}catch(e){console.error(e);setStatus('system-status',`主檔同步失敗：${e.message}`,'error')}finally{S.syncing=false;if(b)b.disabled=false}}
function resolveFromMaster(q0){const q=nt(q0).toLowerCase();const rows=Object.values(S.masterData||{}),seen=new Set(),items=[];rows.filter(i=>nt(i.barcode).toLowerCase()===q||nt(i.itemId).toLowerCase()===q||nt(i.barcode).toLowerCase().includes(q)||nt(i.itemId).toLowerCase().includes(q)||nt(i.name).toLowerCase().includes(q)).forEach(i=>{const k=i.itemId+'|'+i.barcode;if(!seen.has(k)){seen.add(k);items.push(i)}});return items.length===0?{type:'NONE'}:items.length===1?{type:'ONE',item:items[0]}:{type:'MULTI',items:items.slice(0,30)}}
function addDraftItem(item,qty){const n=pos(qty,1),f=S.draftItems.find(x=>x.itemId===item.itemId);if(f)f.qty+=n;else S.draftItems.push({itemId:nt(item.itemId),name:nt(item.name),barcode:nt(item.barcode),qty:n});renderDraft()}
async function handleInput(q,qty,source='manual'){q=nt(q);const statusId=source==='scanner'?'scanner-status':'manual-status';if(!q){setStatus(statusId,'請輸入條碼 / 品名 / 品項ID','error');return}if(Object.keys(S.masterData).length===0)await syncMasterData(false);const r=resolveFromMaster(q);if(r.type==='NONE'){setStatus(statusId,`找不到品項：${q}`,'error');return}if(r.type==='ONE'){addDraftItem(r.item,qty);setStatus(statusId,`已加入：${r.item.name}`,'ok');if(source==='manual')$('manual-query').value='';return}S.pendingQty=pos(qty,1);S.choices=r.items;renderChoices();$('picker').classList.remove('hidden');setStatus(statusId,`找到 ${r.items.length} 筆，請選擇品項`,'warn')}
function updateSubmitHint(){const title=nt($('proposal-title')?.value);setText('submit-hint',title?`標題：${title}`:'標題：未命名提案，送出後以系統單號追蹤。')}
function renderDraft(){updateSubmitHint();const root=$('draft-list');root.innerHTML='';if(S.draftItems.length===0){root.innerHTML='<p class="muted">尚無品項</p>';setText('total-badge','品項 0｜總數 0');return}let total=0;S.draftItems.forEach(i=>{total+=i.qty;const c=document.createElement('article');c.className='item-card';const info=document.createElement('div');const n=document.createElement('div');n.className='item-name';n.textContent=i.name;const m=document.createElement('div');m.className='muted';m.textContent=`${i.itemId}｜${i.barcode}`;info.append(n,m);const lab=document.createElement('label');lab.textContent='數量';const qty=document.createElement('input');qty.type='number';qty.min='1';qty.value=i.qty;qty.onchange=()=>{i.qty=pos(qty.value,1);renderDraft()};lab.appendChild(qty);const del=document.createElement('button');del.className='danger';del.textContent='刪除';del.onclick=()=>{S.draftItems=S.draftItems.filter(x=>x.itemId!==i.itemId);renderDraft()};c.append(info,lab,del);root.appendChild(c)});setText('total-badge',`品項 ${S.draftItems.length}｜總數 ${total}`)}
function renderChoices(){const root=$('choice-list');root.innerHTML='';S.choices.forEach(i=>{const c=document.createElement('article');c.className='choice-card';const n=document.createElement('div');n.className='item-name';n.textContent=i.name;const m=document.createElement('div');m.className='muted';m.textContent=`${i.itemId}｜${i.barcode}`;c.append(n,m);c.onclick=()=>{addDraftItem(i,S.pendingQty);$('picker').classList.add('hidden');setStatus('manual-status',`已加入：${i.name}`,'ok')};root.appendChild(c)})}
function switchPage(p){const h=p==='history';$('page-proposal').classList.toggle('hidden',h);$('page-history').classList.toggle('hidden',!h);$('tab-proposal').classList.toggle('active',!h);$('tab-history').classList.toggle('active',h);if(h&&S.historyItems.length===0)setStatus('history-message','請選擇日期查詢，或點今日單據。','warn')}
function todayKey(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}function fmt(v){if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString('zh-TW',{hour12:false})}
async function searchHistory(q){q=nt(q);if(!/^\d{4}-\d{2}-\d{2}$/.test(q)){setStatus('history-message','請選擇有效日期（YYYY-MM-DD）','error');return}if(S.historyLoading)return;S.historyLoading=true;try{setStatus('history-message','查詢中...','warn');const data=await apiRequest('searchHistory',{q});S.historyItems=Array.isArray(data&&data.items)?data.items:Array.isArray(data)?data:[];renderHistoryResults();setStatus('history-message',`查詢完成：${S.historyItems.length} 筆`,S.historyItems.length?'ok':'warn')}catch(e){console.error(e);setStatus('history-message',`查詢失敗：${e.message}`,'error')}finally{S.historyLoading=false}}
function renderHistoryResults(){const root=$('history-results');root.innerHTML='';if(S.historyItems.length===0){const p=document.createElement('p');p.className='muted';p.textContent='尚無查詢結果';root.appendChild(p);return}S.historyItems.forEach(d=>{const card=document.createElement('article');card.className='doc-card';const main=document.createElement('div');main.className='doc-main';const left=document.createElement('div');const id=document.createElement('div');id.className='muted';id.textContent=nt(d.docId);const title=document.createElement('div');title.className='doc-title';title.textContent=nt(d.title)||'未命名提案';left.append(id,title);const right=document.createElement('div');right.className='muted';right.style.textAlign='right';right.textContent=fmt(d.createdAt)+'\n'+(nt(d.status)||'ACTIVE');main.append(left,right);const badges=document.createElement('div');badges.className='badge-row';['品項 '+(d.itemCount??0),'總數 '+(d.totalQty??0)].forEach(t=>{const s=document.createElement('span');s.className='badge';s.textContent=t;badges.appendChild(s)});card.append(main,badges);card.onclick=()=>loadHistoryDetail(d.docId);root.appendChild(card)})}
async function loadHistoryDetail(docId){docId=nt(docId);if(!docId||S.detailLoading)return;S.detailLoading=true;try{const d=await apiRequest('getProposalDetail',{docId});renderHistoryDetail(d);$('detail-modal').classList.remove('hidden')}catch(e){setStatus('history-message',`載入明細失敗：${e.message}`,'error')}finally{S.detailLoading=false}}
function renderHistoryDetail(d){setText('detail-doc-id',d&&d.docId?d.docId:'單據明細');setText('detail-summary',[(d&&d.title)||'未命名提案',fmt(d&&d.createdAt),d&&d.status].filter(Boolean).join('｜'));const root=$('detail-items');root.innerHTML='';const items=Array.isArray(d&&d.items)?d.items:[];items.forEach(i=>{const row=document.createElement('div');row.className='detail-item';const left=document.createElement('div');const n=document.createElement('strong');n.textContent=nt(i.name);const m=document.createElement('div');m.className='muted';m.textContent=`${nt(i.itemId)}｜${nt(i.barcode)}`;left.append(n,m);const q=document.createElement('span');q.className='badge';q.textContent='x '+(i.qty??0);row.append(left,q);root.appendChild(row)})}
async function detectCameras(){const cams=await Html5Qrcode.getCameras();S.cameras=Array.isArray(cams)?cams:[];setText('camera-diagnostic',`cameraCount=${S.cameras.length}\n`+S.cameras.map((c,i)=>`${i+1}. ${c.label||'(未命名)'}`).join('\n'));return S.cameras}
function scanConfig(){return{fps:10,qrbox:250}}async function cleanupScanner(){if(S.scanner){try{await S.scanner.stop()}catch(e){}try{await S.scanner.clear()}catch(e){}}S.scanner=null;$('reader-wrap').classList.remove('active');$('btn-start').disabled=false;$('btn-stop').disabled=true}function onScanSuccess(txt){const code=nt(txt),now=Date.now();if(!code||code===S.lastScanText&&now-S.lastScanAt<CONFIG.SCAN_DEBOUNCE_MS)return;S.lastScanText=code;S.lastScanAt=now;const q=$('manual-query');if(q)q.value=code;setStatus('scanner-status',`已掃描：${code}，解析中...`,'ok');handleInput(code,1,'scanner')}async function startScanner(){if(S.scanner)return;if(typeof Html5Qrcode==='undefined'){setStatus('scanner-status','html5-qrcode 尚未載入','error');return}$('reader-wrap').classList.add('active');$('btn-start').disabled=true;try{let cams=[];try{cams=await detectCameras()}catch(e){}const rear=cams.find(c=>/back|rear|environment|後|背/i.test(nt(c.label)));const id=(rear||cams[0]||{}).id;S.scanner=new Html5Qrcode('reader');await S.scanner.start(id||{facingMode:'environment'},scanConfig(),onScanSuccess,()=>{});$('btn-stop').disabled=false;setStatus('scanner-status','相機已啟動，請對準 QRCode / 條碼','ok')}catch(e){await cleanupScanner();setStatus('scanner-status',`相機啟動失敗：${e.message||e}`,'error')}}async function stopScanner(){await cleanupScanner();setStatus('scanner-status','相機已停止','ok')}function pauseScanner(){try{if(S.scanner&&S.scanner.getState&&S.scanner.getState()===2)S.scanner.pause()}catch(_){}}function resumeScanner(){try{if(S.scanner&&S.scanner.getState&&S.scanner.getState()===3)S.scanner.resume()}catch(_){}}
async function submitProposal(){if(S.submitting)return;const title=nt($('proposal-title').value),source=nt($('proposal-source').value)||'GitHub Pages';if(S.draftItems.length===0){setStatus('submit-status','草稿沒有品項','error');return}S.submitting=true;const btn=$('btn-submit');btn.disabled=true;btn.textContent='送出中...';try{const data=await apiRequest('submitProposal',{title,source,clientRequestId:'uid-'+Date.now(),items:S.draftItems});setStatus('submit-status',`送出成功：${data&&data.docId?data.docId:'已建立單號'}`,'ok');S.draftItems=[];renderDraft();$('proposal-title').value='';updateSubmitHint()}catch(e){setStatus('submit-status',`送出失敗：${e.message}`,'error')}finally{S.submitting=false;btn.disabled=false;btn.textContent='送出提案'}}
function bind(){$('tab-proposal').onclick=()=>switchPage('proposal');$('tab-history').onclick=()=>switchPage('history');$('btn-history-search').onclick=()=>searchHistory($('history-date').value);$('btn-history-today').onclick=()=>{const q=todayKey();$('history-date').value=q;searchHistory(q)};$('history-date').onchange=()=>searchHistory($('history-date').value);$('btn-close-detail').onclick=()=>$('detail-modal').classList.add('hidden');$('detail-modal').onclick=e=>{if(e.target.id==='detail-modal')$('detail-modal').classList.add('hidden')};$('btn-sync').onclick=()=>syncMasterData(true);$('btn-add').onclick=()=>handleInput($('manual-query').value,$('manual-qty').value,'manual');$('manual-query').onkeydown=e=>{if(e.key==='Enter')handleInput($('manual-query').value,$('manual-qty').value,'manual')};$('proposal-title').oninput=updateSubmitHint;$('btn-submit').onclick=submitProposal;$('btn-clear').onclick=()=>{S.draftItems=[];renderDraft();setStatus('submit-status','草稿已清空','ok')};$('btn-close-picker').onclick=()=>$('picker').classList.add('hidden');$('picker').onclick=e=>{if(e.target.id==='picker')$('picker').classList.add('hidden')};$('btn-cameras').onclick=detectCameras;$('btn-start').onclick=startScanner;$('btn-stop').onclick=stopScanner}
document.addEventListener('DOMContentLoaded',()=>{bind();renderDraft();renderHistoryResults();switchPage('proposal');syncMasterData(false)});
