/*
【目的】
- 核心理由：GitHub Pages SPA：需求提案單 + 歷史單據查詢，共用 GAS API。
- 權責邊界：[負責]前端分頁、MasterData 快取 resolve、提交、歷史查詢/明細、相機基本控制；[不負責]後端 GAS 實作。
- MWE：設定 CONFIG.API_URL 後部署；手動輸入可加入草稿；歷史分頁可查詢單據。
- 致命錯誤邊界：API timeout、Null DOM、HTML injection、重複送出、相機清理已防護；風險受控。
*/
const CONFIG={
 API_URL:'https://script.google.com/macros/s/AKfycbxw9Y1y3A7N5CUhgp0ACezB12JXqNPXcssvMTwwWk5C2QeMCvn97UdrueSQ6_Jx0rJG/exec',
 APP_KEY:'public-mvp-key',CACHE_KEY_VERSION:'proposal_sys_version',CACHE_KEY_DATA:'proposal_sys_master_data',API_TIMEOUT_MS:15000,SCAN_DEBOUNCE_MS:1500
};
const ScannerState=Object.freeze({IDLE:'IDLE',STARTING:'STARTING',RUNNING:'RUNNING',STOPPING:'STOPPING',ERROR:'ERROR'});
const state={masterData:{},currentVersion:'',draftItems:[],scanner:null,scannerState:ScannerState.IDLE,lastScanText:'',lastScanAt:0,choices:[],pendingQty:1,submitting:false,syncing:false,cameras:[],activePage:'proposal',historyItems:[],historyLoading:false,detailLoading:false};
const $=id=>document.getElementById(id);
const setText=(id,text)=>{const el=$(id);if(el)el.textContent=text==null?'':String(text)};
function setStatus(id,msg,type){const el=$(id);if(!el)return;el.textContent=msg==null?'':String(msg);el.className='status';if(type==='error')el.classList.add('error');if(type==='warn')el.classList.add('warn')}
function nt(v){return v==null?'':String(v).trim()}function pos(v,f=1){const n=Number(v);return!Number.isFinite(n)||n<=0?f:Math.floor(n)}
function apiRequest(action,payload={}){const body={action,appKey:CONFIG.APP_KEY,payload};const c=new AbortController();const t=setTimeout(()=>c.abort(),CONFIG.API_TIMEOUT_MS);return fetch(CONFIG.API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body),signal:c.signal}).then(async r=>{const text=await r.text();if(!r.ok)throw new Error(`HTTP ${r.status}: ${text.slice(0,160)}`);try{return JSON.parse(text)}catch(_){throw new Error(`API 回傳不是 JSON：${text.slice(0,160)}`)}}).then(j=>{if(!j||j.success===false)throw new Error(j&&j.message?j.message:'API 失敗');return j.data}).catch(e=>{if(e&&e.name==='AbortError')throw new Error('API 逾時，請檢查 GAS 部署與網路');throw e}).finally(()=>clearTimeout(t))}
async function syncMasterData(force=false){if(state.syncing)return;state.syncing=true;const btn=$('btn-sync');if(btn)btn.disabled=true;try{setStatus('message','同步主檔中...','warn');const rv=await apiRequest('getMasterVersion');const lv=localStorage.getItem(CONFIG.CACHE_KEY_VERSION);if(force||rv!==lv){const items=await apiRequest('getMasterSnapshot');if(!Array.isArray(items))throw new Error('主檔快照格式錯誤，預期為陣列');const map={};items.forEach(i=>{const barcode=nt(i.barcode),itemId=nt(i.itemId),name=nt(i.name);if(barcode&&itemId&&name)map[barcode]={itemId,name,barcode}});state.masterData=map;state.currentVersion=String(rv||'');localStorage.setItem(CONFIG.CACHE_KEY_DATA,JSON.stringify(map));localStorage.setItem(CONFIG.CACHE_KEY_VERSION,state.currentVersion);setStatus('message',`主檔同步完成：${Object.keys(map).length} 筆`,'ok');return}state.masterData=JSON.parse(localStorage.getItem(CONFIG.CACHE_KEY_DATA)||'{}');setStatus('message',`主檔已使用快取：${Object.keys(state.masterData).length} 筆`,'ok')}catch(e){console.error('[SYNC_MASTER_ERROR]',e);setStatus('message',`主檔同步失敗：${e.message}`,'error')}finally{state.syncing=false;if(btn)btn.disabled=false}}
function resolveFromMaster(q0){const q=nt(q0).toLowerCase();if(!q)return{type:'EMPTY',items:[]};const rows=Object.values(state.masterData||{});const exact=rows.filter(i=>nt(i.barcode).toLowerCase()===q||nt(i.itemId).toLowerCase()===q);const fuzzy=rows.filter(i=>nt(i.barcode).toLowerCase().includes(q)||nt(i.itemId).toLowerCase().includes(q)||nt(i.name).toLowerCase().includes(q));const seen=new Set(),items=[];exact.concat(fuzzy).forEach(i=>{const k=`${i.itemId}|${i.barcode}`;if(!seen.has(k)){seen.add(k);items.push(i)}});if(items.length===0)return{type:'NONE',items:[]};if(items.length===1)return{type:'ONE',item:items[0],items};return{type:'MULTI',items:items.slice(0,30)}}
function addDraftItem(item,qty){const n=pos(qty,1),itemId=nt(item.itemId),name=nt(item.name),barcode=nt(item.barcode);if(!itemId||!name||!barcode)throw new Error('品項資料不完整');const f=state.draftItems.find(x=>x.itemId===itemId);if(f)f.qty+=n;else state.draftItems.push({itemId,name,barcode,qty:n});renderDraft()}
async function handleInput(query,qty){const q=nt(query),n=pos(qty,1);if(!q){setStatus('message','請輸入條碼 / 品名 / 品項ID','error');resumeScanner();return}if(Object.keys(state.masterData||{}).length===0)await syncMasterData(false);const r=resolveFromMaster(q);if(r.type==='NONE'){setStatus('message',`找不到品項：${q}`,'error');resumeScanner();return}if(r.type==='ONE'){addDraftItem(r.item,n);setStatus('message',`已加入：${r.item.name}`,'ok');const input=$('manual-query');if(input)input.value='';resumeScanner();return}state.pendingQty=n;state.choices=r.items;renderChoices();showPicker(true);pauseScanner();setStatus('message',`找到 ${r.items.length} 筆，請選擇品項`,'warn')}
function renderDraft(){const root=$('draft-list');if(!root)return;if(state.draftItems.length===0){root.innerHTML='<p class="muted">尚無品項</p>';setText('total-badge','品項 0｜總數 0');return}let total=0;root.innerHTML='';state.draftItems.forEach(item=>{total+=Number(item.qty||0);const card=document.createElement('article');card.className='item-card';const info=document.createElement('div');const name=document.createElement('div');name.className='item-name';name.textContent=item.name;const meta=document.createElement('div');meta.className='muted';meta.textContent=`${item.itemId}｜${item.barcode}`;info.append(name,meta);const lab=document.createElement('label');lab.textContent='數量';const qty=document.createElement('input');qty.type='number';qty.min='1';qty.step='1';qty.value=String(item.qty);qty.addEventListener('change',()=>{item.qty=pos(qty.value,1);qty.value=String(item.qty);renderDraft()});lab.appendChild(qty);const rm=document.createElement('button');rm.className='danger';rm.type='button';rm.textContent='刪除';rm.addEventListener('click',()=>{state.draftItems=state.draftItems.filter(x=>x.itemId!==item.itemId);renderDraft()});card.append(info,lab,rm);root.appendChild(card)});setText('total-badge',`品項 ${state.draftItems.length}｜總數 ${total}`)}
function showPicker(on){const p=$('picker');if(p)p.classList.toggle('hidden',!on)}function closePicker(){showPicker(false);state.choices=[];renderChoices();resumeScanner()}function renderChoices(){const root=$('choice-list');if(!root)return;root.innerHTML='';state.choices.forEach(item=>{const card=document.createElement('article');card.className='choice-card';const name=document.createElement('div');name.className='item-name';name.textContent=item.name;const meta=document.createElement('div');meta.className='muted';meta.textContent=`${item.itemId}｜${item.barcode}`;card.append(name,meta);card.addEventListener('click',()=>{addDraftItem(item,state.pendingQty||1);closePicker();setStatus('message',`已加入：${item.name}`,'ok')});root.appendChild(card)})}
function switchPage(page){state.activePage=page==='history'?'history':'proposal';$('page-proposal')?.classList.toggle('hidden',state.activePage!=='proposal');$('page-history')?.classList.toggle('hidden',state.activePage!=='history');$('tab-proposal')?.classList.toggle('active',state.activePage==='proposal');$('tab-history')?.classList.toggle('active',state.activePage==='history');if(state.activePage==='history'&&state.historyItems.length===0)setStatus('history-message','請輸入條件查詢，或點今日單據。','warn')}
function todayKey(){const d=new Date();return`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`}function fmt(v){if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString('zh-TW',{hour12:false})}
async function searchHistory(query){if(state.historyLoading)return;const q=nt(query);if(!q){setStatus('history-message','請輸入查詢條件','error');return}state.historyLoading=true;const b=$('btn-history-search'),tb=$('btn-history-today');if(b)b.disabled=true;if(tb)tb.disabled=true;try{setStatus('history-message','查詢中...','warn');const data=await apiRequest('searchHistory',{q});const items=Array.isArray(data&&data.items)?data.items:Array.isArray(data)?data:[];state.historyItems=items;renderHistoryResults();setStatus('history-message',`查詢完成：${items.length} 筆`,items.length?'ok':'warn')}catch(e){console.error('[HISTORY_SEARCH_ERROR]',e);setStatus('history-message',`查詢失敗：${e.message}`,'error')}finally{state.historyLoading=false;if(b)b.disabled=false;if(tb)tb.disabled=false}}
function renderHistoryResults(){const root=$('history-results');if(!root)return;root.innerHTML='';if(state.historyItems.length===0){const p=document.createElement('p');p.className='muted';p.textContent='尚無查詢結果';root.appendChild(p);return}state.historyItems.forEach(doc=>{const card=document.createElement('article');card.className='doc-card';card.tabIndex=0;const main=document.createElement('div');main.className='doc-main';const left=document.createElement('div');const id=document.createElement('div');id.className='muted';id.textContent=nt(doc.docId)||'(無單號)';const title=document.createElement('div');title.className='doc-title';title.textContent=nt(doc.title)||'(未命名)';const first=document.createElement('div');first.className='muted';first.textContent=nt(doc.firstItemName||doc.source||'');left.append(id,title,first);const right=document.createElement('div');right.className='muted';right.style.textAlign='right';const created=document.createElement('div');created.textContent=fmt(doc.createdAt);const status=document.createElement('div');status.textContent=nt(doc.status)||'ACTIVE';right.append(created,status);main.append(left,right);const badges=document.createElement('div');badges.className='badge-row';['品項 '+(doc.itemCount??0),'總數 '+(doc.totalQty??0)].forEach(t=>{const s=document.createElement('span');s.className='badge';s.textContent=t;badges.appendChild(s)});card.append(main,badges);card.addEventListener('click',()=>loadHistoryDetail(doc.docId));card.addEventListener('keydown',e=>{if(e.key==='Enter')loadHistoryDetail(doc.docId)});root.appendChild(card)})}
async function loadHistoryDetail(docId){const id=nt(docId);if(!id||state.detailLoading)return;state.detailLoading=true;try{setStatus('history-message',`載入明細：${id}`,'warn');const d=await apiRequest('getProposalDetail',{docId:id});renderHistoryDetail(d);showDetailModal(true);setStatus('history-message',`已載入：${id}`,'ok')}catch(e){console.error('[HISTORY_DETAIL_ERROR]',e);setStatus('history-message',`載入明細失敗：${e.message}`,'error')}finally{state.detailLoading=false}}
function showDetailModal(on){$('detail-modal')?.classList.toggle('hidden',!on)}function closeDetailModal(){showDetailModal(false)}function renderHistoryDetail(d){setText('detail-doc-id',d&&d.docId?d.docId:'單據明細');const summary=[];if(d&&d.title)summary.push(d.title);if(d&&d.createdAt)summary.push(fmt(d.createdAt));if(d&&d.status)summary.push(d.status);setText('detail-summary',summary.join('｜'));const root=$('detail-items');if(!root)return;root.innerHTML='';const items=Array.isArray(d&&d.items)?d.items:[];if(items.length===0){const p=document.createElement('p');p.className='muted';p.textContent='沒有明細項目';root.appendChild(p);return}items.forEach(item=>{const row=document.createElement('div');row.className='detail-item';const left=document.createElement('div');const name=document.createElement('strong');name.textContent=nt(item.name)||'(未命名品項)';const meta=document.createElement('div');meta.className='muted';meta.textContent=`${nt(item.itemId)}｜${nt(item.barcode)}`;left.append(name,meta);const qty=document.createElement('div');qty.className='badge';qty.textContent=`x ${item.qty??0}`;row.append(left,qty);root.appendChild(row)})}
function setScannerState(next,msg,type){state.scannerState=next;const busy=next===ScannerState.STARTING||next===ScannerState.STOPPING;const running=next===ScannerState.RUNNING;$('btn-start')&&( $('btn-start').disabled=busy||running );$('btn-stop')&&( $('btn-stop').disabled=!(state.scanner||busy||running||next===ScannerState.ERROR) );setStatus('scanner-status',msg||next,type||(next===ScannerState.ERROR?'error':next===ScannerState.IDLE?'warn':'ok'))}
async function detectCameras(){if(typeof Html5Qrcode==='undefined')throw new Error('html5-qrcode 尚未載入');const cams=await Html5Qrcode.getCameras();state.cameras=Array.isArray(cams)?cams:[];renderCameraDiagnostic();return state.cameras}function renderCameraDiagnostic(extra){const lines=[];lines.push(`secureContext=${String(window.isSecureContext)}`);lines.push(`mediaDevices=${String(Boolean(navigator.mediaDevices&&navigator.mediaDevices.getUserMedia))}`);lines.push(`Html5Qrcode=${String(typeof Html5Qrcode!=='undefined')}`);lines.push(`cameraCount=${state.cameras.length}`);state.cameras.forEach((c,i)=>lines.push(`${i+1}. ${c.label||'(未授權前可能無名稱)'} | ${c.id?c.id.slice(0,12)+'...':'(no id)'}`));if(extra)lines.push(extra);setText('camera-diagnostic',lines.join('\n'))}
async function cleanupScanner(){if(state.scanner){try{await state.scanner.stop()}catch(e){console.warn('[SCANNER_STOP_WARN]',e)}try{await state.scanner.clear()}catch(e){console.warn('[SCANNER_CLEAR_WARN]',e)}}state.scanner=null;$('reader-wrap')?.classList.remove('active');const r=$('reader');if(r)r.innerHTML=''}
function scanConfig(){const f=typeof Html5QrcodeSupportedFormats==='undefined'?null:Html5QrcodeSupportedFormats;const cfg={fps:10,qrbox:(w,h)=>{const e=Math.max(180,Math.floor(Math.min(w,h)*.72));return{width:e,height:e}},aspectRatio:1,disableFlip:false};if(f)cfg.formatsToSupport=[f.QR_CODE,f.CODE_128,f.CODE_39,f.EAN_13,f.EAN_8,f.UPC_A,f.UPC_E].filter(x=>x!==undefined);return cfg}
function onScanSuccess(text){const code=nt(text),now=Date.now();if(!code)return;if(code===state.lastScanText&&now-state.lastScanAt<CONFIG.SCAN_DEBOUNCE_MS)return;state.lastScanText=code;state.lastScanAt=now;if(navigator.vibrate)navigator.vibrate(50);pauseScanner();const q=$('manual-query');if(q)q.value=code;setStatus('scanner-status',`已掃描：${code}，解析中...`,'ok');handleInput(code,1)}
async function startScanner(){if(state.scannerState===ScannerState.STARTING||state.scannerState===ScannerState.RUNNING)return;if(!window.isSecureContext){setScannerState(ScannerState.ERROR,'目前不是安全環境，請使用 HTTPS 或 localhost','error');return}if(typeof Html5Qrcode==='undefined'){setScannerState(ScannerState.ERROR,'html5-qrcode 尚未載入','error');return}setScannerState(ScannerState.STARTING,'正在啟動相機...','warn');await cleanupScanner();$('reader-wrap')?.classList.add('active');try{let cams=[];try{cams=await detectCameras()}catch(e){renderCameraDiagnostic(`getCameras error=${e.message||e}`)}const rear=cams.find(c=>/back|rear|environment|後|背/i.test(nt(c.label)));const id=(rear||cams[0]||{}).id;const attempts=[];if(id)attempts.push({cfg:id,label:'cameraId'});attempts.push({cfg:{facingMode:{exact:'environment'}},label:'environment exact'},{cfg:{facingMode:'environment'},label:'environment ideal'},{cfg:{facingMode:'user'},label:'user camera'});let last=null;for(const a of attempts){try{await cleanupScanner();$('reader-wrap')?.classList.add('active');state.scanner=new Html5Qrcode('reader');await state.scanner.start(a.cfg,scanConfig(),onScanSuccess,()=>{});setScannerState(ScannerState.RUNNING,`相機已啟動：${a.label}`,'ok');return}catch(e){last=e;console.warn('[SCANNER_START_FAIL]',a.label,e);await cleanupScanner()}}throw last||new Error('沒有可用相機啟動方式')}catch(e){console.error('[START_SCANNER_ERROR]',e);await cleanupScanner();setScannerState(ScannerState.ERROR,`相機啟動失敗：${e.message||e}`,'error')}}async function stopScanner(){if(!state.scanner){setScannerState(ScannerState.IDLE,'相機尚未啟動','warn');return}setScannerState(ScannerState.STOPPING,'正在停止相機...','warn');await cleanupScanner();setScannerState(ScannerState.IDLE,'相機已停止','ok')}function pauseScanner(){try{if(state.scanner&&state.scanner.getState&&state.scanner.getState()===2)state.scanner.pause()}catch(_){}}function resumeScanner(){try{if(state.scanner&&state.scanner.getState&&state.scanner.getState()===3)state.scanner.resume()}catch(_){}}
async function submitProposal(){if(state.submitting)return;const title=nt($('proposal-title')&&$('proposal-title').value),source=nt($('proposal-source')&&$('proposal-source').value)||'GitHub Pages';if(!title){setStatus('message','請輸入提案標題','error');return}if(state.draftItems.length===0){setStatus('message','草稿沒有品項','error');return}const btn=$('btn-submit');state.submitting=true;if(btn){btn.disabled=true;btn.textContent='送出中...'}try{const data=await apiRequest('submitProposal',{title,source,clientRequestId:`uid-${Date.now()}-${Math.random().toString(16).slice(2)}`,items:state.draftItems.map(i=>({itemId:i.itemId,name:i.name,barcode:i.barcode,qty:pos(i.qty,1)}))});setStatus('message',`送出成功：${data&&data.docId?data.docId:''}`,'ok');state.draftItems=[];renderDraft();const t=$('proposal-title');if(t)t.value=''}catch(e){console.error('[SUBMIT_ERROR]',e);setStatus('message',`送出失敗：${e.message}`,'error')}finally{state.submitting=false;if(btn){btn.disabled=false;btn.textContent='送出提案'}}}
function clearDraft(){state.draftItems=[];renderDraft();setStatus('message','草稿已清空','ok')}
function bindEvents(){$('tab-proposal')?.addEventListener('click',()=>switchPage('proposal'));$('tab-history')?.addEventListener('click',()=>switchPage('history'));$('btn-history-search')?.addEventListener('click',()=>searchHistory($('history-query')?.value));$('btn-history-today')?.addEventListener('click',()=>{const q=todayKey();const input=$('history-query');if(input)input.value=q;searchHistory(q)});$('history-query')?.addEventListener('keydown',e=>{if(e.key==='Enter')searchHistory($('history-query')?.value)});$('btn-close-detail')?.addEventListener('click',closeDetailModal);$('detail-modal')?.addEventListener('click',e=>{if(e.target&&e.target.id==='detail-modal')closeDetailModal()});$('btn-start')?.addEventListener('click',startScanner);$('btn-stop')?.addEventListener('click',stopScanner);$('btn-cameras')?.addEventListener('click',async()=>{try{await detectCameras();setStatus('scanner-status',`相機檢查完成：${state.cameras.length} 個裝置`,state.cameras.length?'ok':'error')}catch(e){setStatus('scanner-status',`相機檢查失敗：${e.message}`,'error')}});$('btn-sync')?.addEventListener('click',()=>syncMasterData(true));$('btn-add')?.addEventListener('click',()=>handleInput($('manual-query')?.value,$('manual-qty')?.value));$('manual-query')?.addEventListener('keydown',e=>{if(e.key==='Enter')handleInput($('manual-query')?.value,$('manual-qty')?.value)});$('btn-submit')?.addEventListener('click',submitProposal);$('btn-clear')?.addEventListener('click',clearDraft);$('btn-close-picker')?.addEventListener('click',closePicker);$('picker')?.addEventListener('click',e=>{if(e.target&&e.target.id==='picker')closePicker()})}
function init(){bindEvents();renderDraft();renderHistoryResults();switchPage('proposal');setScannerState(ScannerState.IDLE,'相機尚未啟動','warn');renderCameraDiagnostic();syncMasterData(false)}
document.addEventListener('DOMContentLoaded',init);
